### PR TITLE
Fix for auth update, automate minification & README

### LINKED ISSUE #7: Auth change broke script/bookmarklet
I fixed this in #6, but figured it was worth documenting as an issue too. The current version of the script produces this error:

```
Uncaught TypeError: Cannot read properties of undefined (reading 'access_token')
```

Because `Object.keys(localStorage).find(key => key.startsWith('@@auth0spajs@@'))` returns only the first of two results.

### PR DESCRIPTION
**Pull request by kevin-david**
A change broke this script again. This fixes it.

At the same time, I figured it would be good to make minification more verifiable vs checking in random minified files that could do anything.

Fixes #7

### CODE REVIEW

File: source/echelon.js [hunk 1]
```diff
@@ -4,7 +4,7 @@ rideID = rideID[rideID.length - 1];
 
 var bearerToken;
 
-const auth0Key = Object.keys(localStorage).find(key => key.startsWith('@@auth0spajs@@'));
+const auth0Key = Object.keys(localStorage).find(key => key.startsWith('@@auth0spajs@@') && key.indexOf("api.") > 0);
```
Comment (kevin-david) [inline source/echelon.js:7]: Optimally this would be one place instead of three. But didn't feel like getting into that :)
